#############################################################################
# Makefile for building: orayta
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  Orayta.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Orayta.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(shell dpkg-buildflags --get CFLAGS) $(shell dpkg-buildflags --get CPPFLAGS) -D_REENTRANT -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 $(shell dpkg-buildflags --get CFLAGS) $(shell dpkg-buildflags --get CPPFLAGS) -D_REENTRANT -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = orayta1.0.0
DISTDIR = /home/dash/dev/Orayta-QT/.tmp/orayta1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) -lz /usr/lib/libQt5WebKitWidgets.so /usr/lib/libQt5PrintSupport.so /usr/lib/libQt5Widgets.so /usr/lib/libQt5WebKit.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Network.so /usr/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		OraytaBase/booklist.cpp \
		OraytaBase/bookfind.cpp \
		OraytaBase/htmlgen.cpp \
		OraytaBase/functions.cpp \
		OraytaBase/filedownloader.cpp \
		OraytaBase/book.cpp \
		OraytaBase/bookiter.cpp \
		OraytaBase/search.cpp \
		OraytaBase/guematria.cpp \
		OraytaBase/quazip/quazip.cpp \
		OraytaBase/quazip/zip.c \
		OraytaBase/quazip/unzip.c \
		OraytaBase/quazip/quazipnewinfo.cpp \
		OraytaBase/quazip/quazipfile.cpp \
		OraytaBase/quazip/JlCompress.cpp \
		OraytaBase/quazip/quacrc32.cpp \
		OraytaBase/quazip/quaadler32.cpp \
		OraytaBase/quazip/qioapi.cpp \
		OraytaBase/minibmark.cpp \
		OraytaBase/bmarklist.cpp \
		Desktop/desktopapp.cpp \
		Desktop/mywebview.cpp \
		Desktop/mytreetab.cpp \
		Desktop/bookdisplayer.cpp \
		Desktop/addcomment.cpp \
		Desktop/about.cpp \
		Desktop/errorreport.cpp \
		Desktop/settings.cpp \
		Desktop/importbook.cpp \
		Desktop/desktopapp_bookmark.cpp qrc_Orayta.cpp \
		moc_filedownloader.cpp \
		moc_bookfind.cpp \
		moc_quazipfile.cpp \
		moc_minibmark.cpp \
		moc_bmarklist.cpp \
		moc_desktopapp.cpp \
		moc_mywebview.cpp \
		moc_bookdisplayer.cpp \
		moc_addcomment.cpp \
		moc_about.cpp \
		moc_errorreport.cpp \
		moc_settings.cpp \
		moc_importbook.cpp
OBJECTS       = main.o \
		booklist.o \
		bookfind.o \
		htmlgen.o \
		functions.o \
		filedownloader.o \
		book.o \
		bookiter.o \
		search.o \
		guematria.o \
		quazip.o \
		zip.o \
		unzip.o \
		quazipnewinfo.o \
		quazipfile.o \
		JlCompress.o \
		quacrc32.o \
		quaadler32.o \
		qioapi.o \
		minibmark.o \
		bmarklist.o \
		desktopapp.o \
		mywebview.o \
		mytreetab.o \
		bookdisplayer.o \
		addcomment.o \
		about.o \
		errorreport.o \
		settings.o \
		importbook.o \
		desktopapp_bookmark.o \
		qrc_Orayta.o \
		moc_filedownloader.o \
		moc_bookfind.o \
		moc_quazipfile.o \
		moc_minibmark.o \
		moc_bmarklist.o \
		moc_desktopapp.o \
		moc_mywebview.o \
		moc_bookdisplayer.o \
		moc_addcomment.o \
		moc_about.o \
		moc_errorreport.o \
		moc_settings.o \
		moc_importbook.o
DIST          = android-orayta/AndroidManifest.xml \
		android-orayta/res/values/libs.xml \
		android-orayta/build.gradle \
		android-orayta/gradle/wrapper/gradle-wrapper.jar \
		android-orayta/gradlew \
		android-orayta/gradle/wrapper/gradle-wrapper.properties \
		android-orayta/gradlew.bat \
		/usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_CalendarSupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_ContactEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_EventViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_GrantleeTheme.pri \
		/usr/lib/qt/mkspecs/modules/qt_Gravatar.pri \
		/usr/lib/qt/mkspecs/modules/qt_IncidenceEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KaddressbookGrantlee.pri \
		/usr/lib/qt/mkspecs/modules/qt_KaddressbookImportExport.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalendarCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCddb.pri \
		/usr/lib/qt/mkspecs/modules/qt_KChart.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompactDisc.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_kdav.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGantt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPICore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMailTransportAkonadi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KManageSieve.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSieve.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSieveUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSMTP.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTNef.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_Ldap.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_Libkdepim.pri \
		/usr/lib/qt/mkspecs/modules/qt_Libkleo.pri \
		/usr/lib/qt/mkspecs/modules/qt_MailCommon.pri \
		/usr/lib/qt/mkspecs/modules/qt_MailImporter.pri \
		/usr/lib/qt/mkspecs/modules/qt_MailImporterAkonadi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Marble.pri \
		/usr/lib/qt/mkspecs/modules/qt_Mbox.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageComposer.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageList.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageViewer.pri \
		/usr/lib/qt/mkspecs/modules/qt_OktetaCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_OktetaGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_PimCommon.pri \
		/usr/lib/qt/mkspecs/modules/qt_PimCommonAkonadi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_Qt5Keychain.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/qt/mkspecs/modules/qt_TemplateParser.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/modules/qt_WebEngineViewer.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		Orayta.pro OraytaBase/htmlgen.h \
		OraytaBase/functions.h \
		OraytaBase/filedownloader.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/booklist.h \
		OraytaBase/bookfind.h \
		OraytaBase/guematria.h \
		OraytaBase/search.h \
		OraytaBase/quazip/quazip.h \
		OraytaBase/quazip/zip.h \
		OraytaBase/quazip/unzip.h \
		OraytaBase/quazip/quazipnewinfo.h \
		OraytaBase/quazip/quazipfileinfo.h \
		OraytaBase/quazip/quazipfile.h \
		OraytaBase/quazip/quazip_global.h \
		OraytaBase/quazip/JlCompress.h \
		OraytaBase/quazip/ioapi.h \
		OraytaBase/quazip/crypt.h \
		OraytaBase/quazip/quacrc32.h \
		OraytaBase/quazip/quachecksum32.h \
		OraytaBase/quazip/quaadler32.h \
		OraytaBase/minibmark.h \
		OraytaBase/bmarklist.h \
		Desktop/desktopapp.h \
		Desktop/mywebview.h \
		Desktop/mytreetab.h \
		Desktop/bookdisplayer.h \
		Desktop/addcomment.h \
		Desktop/about.h \
		Desktop/errorreport.h \
		Desktop/settings.h \
		Desktop/importbook.h main.cpp \
		OraytaBase/booklist.cpp \
		OraytaBase/bookfind.cpp \
		OraytaBase/htmlgen.cpp \
		OraytaBase/functions.cpp \
		OraytaBase/filedownloader.cpp \
		OraytaBase/book.cpp \
		OraytaBase/bookiter.cpp \
		OraytaBase/search.cpp \
		OraytaBase/guematria.cpp \
		OraytaBase/quazip/quazip.cpp \
		OraytaBase/quazip/zip.c \
		OraytaBase/quazip/unzip.c \
		OraytaBase/quazip/quazipnewinfo.cpp \
		OraytaBase/quazip/quazipfile.cpp \
		OraytaBase/quazip/JlCompress.cpp \
		OraytaBase/quazip/quacrc32.cpp \
		OraytaBase/quazip/quaadler32.cpp \
		OraytaBase/quazip/qioapi.cpp \
		OraytaBase/minibmark.cpp \
		OraytaBase/bmarklist.cpp \
		Desktop/desktopapp.cpp \
		Desktop/mywebview.cpp \
		Desktop/mytreetab.cpp \
		Desktop/bookdisplayer.cpp \
		Desktop/addcomment.cpp \
		Desktop/about.cpp \
		Desktop/errorreport.cpp \
		Desktop/settings.cpp \
		Desktop/importbook.cpp \
		Desktop/desktopapp_bookmark.cpp
QMAKE_TARGET  = orayta
DESTDIR       = 
TARGET        = orayta


first: all
####### Build rules

orayta: ui_bookfind.h ui_addcomment.h ui_about.h ui_errorreport.h ui_settings.h ui_importbook.h ui_desktopapp.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Orayta.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_CalendarSupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_ContactEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_EventViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_GrantleeTheme.pri \
		/usr/lib/qt/mkspecs/modules/qt_Gravatar.pri \
		/usr/lib/qt/mkspecs/modules/qt_IncidenceEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KaddressbookGrantlee.pri \
		/usr/lib/qt/mkspecs/modules/qt_KaddressbookImportExport.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalendarCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCddb.pri \
		/usr/lib/qt/mkspecs/modules/qt_KChart.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompactDisc.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_kdav.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGantt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPICore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMailTransportAkonadi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KManageSieve.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSieve.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSieveUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSMTP.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTNef.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_Ldap.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_Libkdepim.pri \
		/usr/lib/qt/mkspecs/modules/qt_Libkleo.pri \
		/usr/lib/qt/mkspecs/modules/qt_MailCommon.pri \
		/usr/lib/qt/mkspecs/modules/qt_MailImporter.pri \
		/usr/lib/qt/mkspecs/modules/qt_MailImporterAkonadi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Marble.pri \
		/usr/lib/qt/mkspecs/modules/qt_Mbox.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageComposer.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageList.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageViewer.pri \
		/usr/lib/qt/mkspecs/modules/qt_OktetaCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_OktetaGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_PimCommon.pri \
		/usr/lib/qt/mkspecs/modules/qt_PimCommonAkonadi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_Qt5Keychain.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/qt/mkspecs/modules/qt_TemplateParser.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/modules/qt_WebEngineViewer.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		Orayta.pro \
		Orayta.qrc
	$(QMAKE) -o Makefile Orayta.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiAgentBase.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiCalendar.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiContact.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiCore.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiMime.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiNotes.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiXml.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_Baloo.pri:
/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/qt/mkspecs/modules/qt_CalendarSupport.pri:
/usr/lib/qt/mkspecs/modules/qt_ContactEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_EventViews.pri:
/usr/lib/qt/mkspecs/modules/qt_GrantleeTheme.pri:
/usr/lib/qt/mkspecs/modules/qt_Gravatar.pri:
/usr/lib/qt/mkspecs/modules/qt_IncidenceEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/qt/mkspecs/modules/qt_KaddressbookGrantlee.pri:
/usr/lib/qt/mkspecs/modules/qt_KaddressbookImportExport.pri:
/usr/lib/qt/mkspecs/modules/qt_KAlarmCal.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCalendarCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KCalUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCddb.pri:
/usr/lib/qt/mkspecs/modules/qt_KChart.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompactDisc.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KContacts.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_kdav.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri:
/usr/lib/qt/mkspecs/modules/qt_KGantt.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPIBlogger.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPICalendar.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPIContacts.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPICore.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPIDrive.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPILatitude.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPIMaps.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPITasks.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt/mkspecs/modules/qt_KHtml.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdentityManagement.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIMAP.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt/mkspecs/modules/qt_KMailTransport.pri:
/usr/lib/qt/mkspecs/modules/qt_KMailTransportAkonadi.pri:
/usr/lib/qt/mkspecs/modules/qt_KManageSieve.pri:
/usr/lib/qt/mkspecs/modules/qt_KMime.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KontactInterface.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KPIMTextEdit.pri:
/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KrossCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KrossUi.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KScreen.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSieve.pri:
/usr/lib/qt/mkspecs/modules/qt_KSieveUi.pri:
/usr/lib/qt/mkspecs/modules/qt_KSMTP.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KTNef.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_Ldap.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_networkauth.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_Libkdepim.pri:
/usr/lib/qt/mkspecs/modules/qt_Libkleo.pri:
/usr/lib/qt/mkspecs/modules/qt_MailCommon.pri:
/usr/lib/qt/mkspecs/modules/qt_MailImporter.pri:
/usr/lib/qt/mkspecs/modules/qt_MailImporterAkonadi.pri:
/usr/lib/qt/mkspecs/modules/qt_Marble.pri:
/usr/lib/qt/mkspecs/modules/qt_Mbox.pri:
/usr/lib/qt/mkspecs/modules/qt_MessageComposer.pri:
/usr/lib/qt/mkspecs/modules/qt_MessageCore.pri:
/usr/lib/qt/mkspecs/modules/qt_MessageList.pri:
/usr/lib/qt/mkspecs/modules/qt_MessageViewer.pri:
/usr/lib/qt/mkspecs/modules/qt_OktetaCore.pri:
/usr/lib/qt/mkspecs/modules/qt_OktetaGui.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_PimCommon.pri:
/usr/lib/qt/mkspecs/modules/qt_PimCommonAkonadi.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_Qt5Keychain.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_Syndication.pri:
/usr/lib/qt/mkspecs/modules/qt_TemplateParser.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/modules/qt_WebEngineViewer.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources_functions.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
Orayta.pro:
Orayta.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile Orayta.pro

qmake_all: FORCE


all: Makefile orayta

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Orayta.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents OraytaBase/htmlgen.h OraytaBase/functions.h OraytaBase/filedownloader.h OraytaBase/book.h OraytaBase/bookiter.h OraytaBase/booklist.h OraytaBase/bookfind.h OraytaBase/guematria.h OraytaBase/search.h OraytaBase/quazip/quazip.h OraytaBase/quazip/zip.h OraytaBase/quazip/unzip.h OraytaBase/quazip/quazipnewinfo.h OraytaBase/quazip/quazipfileinfo.h OraytaBase/quazip/quazipfile.h OraytaBase/quazip/quazip_global.h OraytaBase/quazip/JlCompress.h OraytaBase/quazip/ioapi.h OraytaBase/quazip/crypt.h OraytaBase/quazip/quacrc32.h OraytaBase/quazip/quachecksum32.h OraytaBase/quazip/quaadler32.h OraytaBase/minibmark.h OraytaBase/bmarklist.h Desktop/desktopapp.h Desktop/mywebview.h Desktop/mytreetab.h Desktop/bookdisplayer.h Desktop/addcomment.h Desktop/about.h Desktop/errorreport.h Desktop/settings.h Desktop/importbook.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp OraytaBase/booklist.cpp OraytaBase/bookfind.cpp OraytaBase/htmlgen.cpp OraytaBase/functions.cpp OraytaBase/filedownloader.cpp OraytaBase/book.cpp OraytaBase/bookiter.cpp OraytaBase/search.cpp OraytaBase/guematria.cpp OraytaBase/quazip/quazip.cpp OraytaBase/quazip/zip.c OraytaBase/quazip/unzip.c OraytaBase/quazip/quazipnewinfo.cpp OraytaBase/quazip/quazipfile.cpp OraytaBase/quazip/JlCompress.cpp OraytaBase/quazip/quacrc32.cpp OraytaBase/quazip/quaadler32.cpp OraytaBase/quazip/qioapi.cpp OraytaBase/minibmark.cpp OraytaBase/bmarklist.cpp Desktop/desktopapp.cpp Desktop/mywebview.cpp Desktop/mytreetab.cpp Desktop/bookdisplayer.cpp Desktop/addcomment.cpp Desktop/about.cpp Desktop/errorreport.cpp Desktop/settings.cpp Desktop/importbook.cpp Desktop/desktopapp_bookmark.cpp $(DISTDIR)/
	$(COPY_FILE) --parents OraytaBase/bookfind.ui Desktop/addcomment.ui Desktop/about.ui Desktop/errorreport.ui Desktop/settings.ui Desktop/importbook.ui Desktop/desktopapp.ui $(DISTDIR)/
	$(COPY_FILE) --parents Hebrew.ts French.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_Orayta.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Orayta.cpp
qrc_Orayta.cpp: Orayta.qrc \
		/usr/bin/rcc \
		OraytaBase/DailyLimud.csv \
		Icons/tab-new2.png \
		Icons/help-contents.png \
		Icons/go-next-view-page.png \
		Icons/search-icon.png \
		Icons/doublegreenv.png \
		Icons/book-html.png \
		Icons/configure.png \
		Icons/back.png \
		Icons/go-previous.png \
		Icons/exit.png \
		Icons/folder-blue-grey.png \
		Icons/folder-user.png \
		Icons/greenv.png \
		Icons/edit.png \
		Icons/search-big.png \
		Icons/dl-book.png \
		Icons/edit-delete.png \
		Icons/tab-close.png \
		Icons/book-pdf.png \
		Icons/doublegreyv.png \
		Icons/copy-clean.png \
		Icons/bookcase.png \
		Icons/booksearch.png \
		Icons/book-grey.png \
		Icons/bookmarks-big.png \
		Icons/go-home.png \
		Icons/bookmarks.png \
		Icons/search-right.png \
		Icons/edit-find.png \
		Icons/arrow-down.png \
		Icons/search-left.png \
		Icons/greyv.png \
		Icons/go-previous-view-page.png \
		Icons/folder-blue.png \
		Icons/book-user.png \
		Icons/zoom-out.png \
		Icons/arrow-right.png \
		Icons/document-print.png \
		Icons/folder-grey.png \
		Icons/help-about-big.png \
		Icons/bookcase-big.png \
		Icons/book-grey-double.png \
		Icons/font.png \
		Icons/Orayta.ico \
		Icons/mail-forward.png \
		Icons/edit-copy.png \
		Icons/tab-new.png \
		Icons/find-big.png \
		Icons/book-blue.png \
		Icons/refresh.png \
		Icons/Orayta-Huge.png \
		Icons/help-about.png \
		Icons/arrow-left.png \
		Icons/book-blue-double.png \
		Icons/bug.png \
		Icons/search.png \
		Icons/help-contents-big.png \
		Icons/zoom-in.png \
		Icons/arrow-up.png \
		Icons/Orayta.png \
		Icons/go-next.png \
		Images/Wait.gif \
		Images/ajax-loader.gif \
		Images/spalsh-portrait.png \
		Images/Orayta.png
	/usr/bin/rcc -name Orayta Orayta.qrc -o qrc_Orayta.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 $(shell dpkg-buildflags --get CFLAGS) $(shell dpkg-buildflags --get CPPFLAGS) -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_filedownloader.cpp moc_bookfind.cpp moc_quazipfile.cpp moc_minibmark.cpp moc_bmarklist.cpp moc_desktopapp.cpp moc_mywebview.cpp moc_bookdisplayer.cpp moc_addcomment.cpp moc_about.cpp moc_errorreport.cpp moc_settings.cpp moc_importbook.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_filedownloader.cpp moc_bookfind.cpp moc_quazipfile.cpp moc_minibmark.cpp moc_bmarklist.cpp moc_desktopapp.cpp moc_mywebview.cpp moc_bookdisplayer.cpp moc_addcomment.cpp moc_about.cpp moc_errorreport.cpp moc_settings.cpp moc_importbook.cpp
moc_filedownloader.cpp: OraytaBase/filedownloader.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/dash/dev/Orayta-QT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dash/dev/Orayta-QT -I/home/dash/dev/Orayta-QT -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include OraytaBase/filedownloader.h -o moc_filedownloader.cpp

moc_bookfind.cpp: OraytaBase/bookfind.h \
		OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/dash/dev/Orayta-QT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dash/dev/Orayta-QT -I/home/dash/dev/Orayta-QT -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include OraytaBase/bookfind.h -o moc_bookfind.cpp

moc_quazipfile.cpp: OraytaBase/quazip/quazipfile.h \
		OraytaBase/quazip/quazip_global.h \
		OraytaBase/quazip/quazip.h \
		OraytaBase/quazip/zip.h \
		OraytaBase/quazip/ioapi.h \
		OraytaBase/quazip/unzip.h \
		OraytaBase/quazip/quazipfileinfo.h \
		OraytaBase/quazip/quazipnewinfo.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/dash/dev/Orayta-QT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dash/dev/Orayta-QT -I/home/dash/dev/Orayta-QT -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include OraytaBase/quazip/quazipfile.h -o moc_quazipfile.cpp

moc_minibmark.cpp: OraytaBase/minibmark.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/dash/dev/Orayta-QT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dash/dev/Orayta-QT -I/home/dash/dev/Orayta-QT -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include OraytaBase/minibmark.h -o moc_minibmark.cpp

moc_bmarklist.cpp: OraytaBase/bmarklist.h \
		OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/dash/dev/Orayta-QT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dash/dev/Orayta-QT -I/home/dash/dev/Orayta-QT -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include OraytaBase/bmarklist.h -o moc_bmarklist.cpp

moc_desktopapp.cpp: Desktop/desktopapp.h \
		ui_desktopapp.h \
		Desktop/mytreetab.h \
		OraytaBase/bmarklist.h \
		OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/dash/dev/Orayta-QT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dash/dev/Orayta-QT -I/home/dash/dev/Orayta-QT -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include Desktop/desktopapp.h -o moc_desktopapp.cpp

moc_mywebview.cpp: Desktop/mywebview.h \
		OraytaBase/functions.h \
		Desktop/desktopapp.h \
		ui_desktopapp.h \
		Desktop/mytreetab.h \
		OraytaBase/bmarklist.h \
		OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/guematria.h \
		Desktop/bookdisplayer.h \
		Desktop/pdfwidget.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/dash/dev/Orayta-QT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dash/dev/Orayta-QT -I/home/dash/dev/Orayta-QT -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include Desktop/mywebview.h -o moc_mywebview.cpp

moc_bookdisplayer.cpp: Desktop/bookdisplayer.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		OraytaBase/booklist.h \
		Desktop/pdfwidget.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/dash/dev/Orayta-QT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dash/dev/Orayta-QT -I/home/dash/dev/Orayta-QT -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include Desktop/bookdisplayer.h -o moc_bookdisplayer.cpp

moc_addcomment.cpp: Desktop/addcomment.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/dash/dev/Orayta-QT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dash/dev/Orayta-QT -I/home/dash/dev/Orayta-QT -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include Desktop/addcomment.h -o moc_addcomment.cpp

moc_about.cpp: Desktop/about.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/dash/dev/Orayta-QT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dash/dev/Orayta-QT -I/home/dash/dev/Orayta-QT -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include Desktop/about.h -o moc_about.cpp

moc_errorreport.cpp: Desktop/errorreport.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/dash/dev/Orayta-QT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dash/dev/Orayta-QT -I/home/dash/dev/Orayta-QT -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include Desktop/errorreport.h -o moc_errorreport.cpp

moc_settings.cpp: Desktop/settings.h \
		Desktop/desktopapp.h \
		ui_desktopapp.h \
		Desktop/mytreetab.h \
		OraytaBase/bmarklist.h \
		OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/dash/dev/Orayta-QT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dash/dev/Orayta-QT -I/home/dash/dev/Orayta-QT -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include Desktop/settings.h -o moc_settings.cpp

moc_importbook.cpp: Desktop/importbook.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/dash/dev/Orayta-QT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dash/dev/Orayta-QT -I/home/dash/dev/Orayta-QT -I/usr/include/qt -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include Desktop/importbook.h -o moc_importbook.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_bookfind.h ui_addcomment.h ui_about.h ui_errorreport.h ui_settings.h ui_importbook.h ui_desktopapp.h
compiler_uic_clean:
	-$(DEL_FILE) ui_bookfind.h ui_addcomment.h ui_about.h ui_errorreport.h ui_settings.h ui_importbook.h ui_desktopapp.h
ui_bookfind.h: OraytaBase/bookfind.ui \
		/usr/bin/uic
	/usr/bin/uic OraytaBase/bookfind.ui -o ui_bookfind.h

ui_addcomment.h: Desktop/addcomment.ui \
		/usr/bin/uic
	/usr/bin/uic Desktop/addcomment.ui -o ui_addcomment.h

ui_about.h: Desktop/about.ui \
		/usr/bin/uic
	/usr/bin/uic Desktop/about.ui -o ui_about.h

ui_errorreport.h: Desktop/errorreport.ui \
		/usr/bin/uic
	/usr/bin/uic Desktop/errorreport.ui -o ui_errorreport.h

ui_settings.h: Desktop/settings.ui \
		/usr/bin/uic
	/usr/bin/uic Desktop/settings.ui -o ui_settings.h

ui_importbook.h: Desktop/importbook.ui \
		/usr/bin/uic
	/usr/bin/uic Desktop/importbook.ui -o ui_importbook.h

ui_desktopapp.h: Desktop/desktopapp.ui \
		/usr/bin/uic \
		OraytaBase/bmarklist.h \
		Desktop/mytreetab.h \
		OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h
	/usr/bin/uic Desktop/desktopapp.ui -o ui_desktopapp.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp Mobile/mobileapp.h \
		OraytaBase/filedownloader.h \
		OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		OraytaBase/bookfind.h \
		Mobile/textdisplayer.h \
		Desktop/desktopapp.h \
		ui_desktopapp.h \
		Desktop/mytreetab.h \
		OraytaBase/bmarklist.h \
		Desktop/about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

booklist.o: OraytaBase/booklist.cpp OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o booklist.o OraytaBase/booklist.cpp

bookfind.o: OraytaBase/bookfind.cpp OraytaBase/bookfind.h \
		OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		ui_bookfind.h \
		Desktop/desktopapp.h \
		ui_desktopapp.h \
		Desktop/mytreetab.h \
		OraytaBase/bmarklist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bookfind.o OraytaBase/bookfind.cpp

htmlgen.o: OraytaBase/htmlgen.cpp OraytaBase/htmlgen.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		OraytaBase/booklist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o htmlgen.o OraytaBase/htmlgen.cpp

functions.o: OraytaBase/functions.cpp OraytaBase/functions.h \
		OraytaBase/quazip/quazipfile.h \
		OraytaBase/quazip/quazip_global.h \
		OraytaBase/quazip/quazip.h \
		OraytaBase/quazip/zip.h \
		OraytaBase/quazip/ioapi.h \
		OraytaBase/quazip/unzip.h \
		OraytaBase/quazip/quazipfileinfo.h \
		OraytaBase/quazip/quazipnewinfo.h \
		Mobile/jnifunc.h \
		OraytaBase/bookiter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functions.o OraytaBase/functions.cpp

filedownloader.o: OraytaBase/filedownloader.cpp OraytaBase/filedownloader.h \
		OraytaBase/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filedownloader.o OraytaBase/filedownloader.cpp

book.o: OraytaBase/book.cpp OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o book.o OraytaBase/book.cpp

bookiter.o: OraytaBase/bookiter.cpp OraytaBase/bookiter.h \
		OraytaBase/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bookiter.o OraytaBase/bookiter.cpp

search.o: OraytaBase/search.cpp OraytaBase/htmlgen.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		OraytaBase/search.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o search.o OraytaBase/search.cpp

guematria.o: OraytaBase/guematria.cpp OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guematria.o OraytaBase/guematria.cpp

quazip.o: OraytaBase/quazip/quazip.cpp OraytaBase/quazip/quazip.h \
		OraytaBase/quazip/zip.h \
		OraytaBase/quazip/ioapi.h \
		OraytaBase/quazip/unzip.h \
		OraytaBase/quazip/quazip_global.h \
		OraytaBase/quazip/quazipfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazip.o OraytaBase/quazip/quazip.cpp

zip.o: OraytaBase/quazip/zip.c OraytaBase/quazip/zip.h \
		OraytaBase/quazip/ioapi.h \
		OraytaBase/quazip/quazip_global.h \
		OraytaBase/quazip/crypt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o zip.o OraytaBase/quazip/zip.c

unzip.o: OraytaBase/quazip/unzip.c OraytaBase/quazip/unzip.h \
		OraytaBase/quazip/ioapi.h \
		OraytaBase/quazip/crypt.h \
		OraytaBase/quazip/quazip_global.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o unzip.o OraytaBase/quazip/unzip.c

quazipnewinfo.o: OraytaBase/quazip/quazipnewinfo.cpp OraytaBase/quazip/quazipnewinfo.h \
		OraytaBase/quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipnewinfo.o OraytaBase/quazip/quazipnewinfo.cpp

quazipfile.o: OraytaBase/quazip/quazipfile.cpp OraytaBase/quazip/quazipfile.h \
		OraytaBase/quazip/quazip_global.h \
		OraytaBase/quazip/quazip.h \
		OraytaBase/quazip/zip.h \
		OraytaBase/quazip/ioapi.h \
		OraytaBase/quazip/unzip.h \
		OraytaBase/quazip/quazipfileinfo.h \
		OraytaBase/quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipfile.o OraytaBase/quazip/quazipfile.cpp

JlCompress.o: OraytaBase/quazip/JlCompress.cpp OraytaBase/quazip/JlCompress.h \
		OraytaBase/quazip/quazip.h \
		OraytaBase/quazip/zip.h \
		OraytaBase/quazip/ioapi.h \
		OraytaBase/quazip/unzip.h \
		OraytaBase/quazip/quazip_global.h \
		OraytaBase/quazip/quazipfileinfo.h \
		OraytaBase/quazip/quazipfile.h \
		OraytaBase/quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JlCompress.o OraytaBase/quazip/JlCompress.cpp

quacrc32.o: OraytaBase/quazip/quacrc32.cpp OraytaBase/quazip/quacrc32.h \
		OraytaBase/quazip/quachecksum32.h \
		OraytaBase/quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quacrc32.o OraytaBase/quazip/quacrc32.cpp

quaadler32.o: OraytaBase/quazip/quaadler32.cpp OraytaBase/quazip/quaadler32.h \
		OraytaBase/quazip/quachecksum32.h \
		OraytaBase/quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quaadler32.o OraytaBase/quazip/quaadler32.cpp

qioapi.o: OraytaBase/quazip/qioapi.cpp OraytaBase/quazip/ioapi.h \
		OraytaBase/quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qioapi.o OraytaBase/quazip/qioapi.cpp

minibmark.o: OraytaBase/minibmark.cpp OraytaBase/minibmark.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minibmark.o OraytaBase/minibmark.cpp

bmarklist.o: OraytaBase/bmarklist.cpp OraytaBase/bmarklist.h \
		OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		OraytaBase/minibmark.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bmarklist.o OraytaBase/bmarklist.cpp

desktopapp.o: Desktop/desktopapp.cpp OraytaBase/functions.h \
		OraytaBase/htmlgen.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/guematria.h \
		OraytaBase/search.h \
		OraytaBase/quazip/quazip.h \
		OraytaBase/quazip/zip.h \
		OraytaBase/quazip/ioapi.h \
		OraytaBase/quazip/unzip.h \
		OraytaBase/quazip/quazip_global.h \
		OraytaBase/quazip/quazipfileinfo.h \
		OraytaBase/quazip/quazipfile.h \
		OraytaBase/quazip/quazipnewinfo.h \
		OraytaBase/bookfind.h \
		OraytaBase/booklist.h \
		Desktop/desktopapp.h \
		ui_desktopapp.h \
		Desktop/mytreetab.h \
		OraytaBase/bmarklist.h \
		Desktop/addcomment.h \
		Desktop/mywebview.h \
		Desktop/bookdisplayer.h \
		Desktop/pdfwidget.h \
		Desktop/about.h \
		Desktop/settings.h \
		Desktop/errorreport.h \
		Desktop/importbook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o desktopapp.o Desktop/desktopapp.cpp

mywebview.o: Desktop/mywebview.cpp Desktop/mywebview.h \
		OraytaBase/functions.h \
		Desktop/desktopapp.h \
		ui_desktopapp.h \
		Desktop/mytreetab.h \
		OraytaBase/bmarklist.h \
		OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/guematria.h \
		Desktop/bookdisplayer.h \
		Desktop/pdfwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mywebview.o Desktop/mywebview.cpp

mytreetab.o: Desktop/mytreetab.cpp Desktop/mytreetab.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mytreetab.o Desktop/mytreetab.cpp

bookdisplayer.o: Desktop/bookdisplayer.cpp Desktop/bookdisplayer.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		OraytaBase/booklist.h \
		Desktop/pdfwidget.h \
		Desktop/desktopapp.h \
		ui_desktopapp.h \
		Desktop/mytreetab.h \
		OraytaBase/bmarklist.h \
		Desktop/mywebview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bookdisplayer.o Desktop/bookdisplayer.cpp

addcomment.o: Desktop/addcomment.cpp Desktop/addcomment.h \
		ui_addcomment.h \
		OraytaBase/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addcomment.o Desktop/addcomment.cpp

about.o: Desktop/about.cpp Desktop/about.h \
		ui_about.h \
		OraytaBase/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o Desktop/about.cpp

errorreport.o: Desktop/errorreport.cpp Desktop/errorreport.h \
		OraytaBase/functions.h \
		Desktop/desktopapp.h \
		ui_desktopapp.h \
		Desktop/mytreetab.h \
		OraytaBase/bmarklist.h \
		OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/guematria.h \
		ui_errorreport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errorreport.o Desktop/errorreport.cpp

settings.o: Desktop/settings.cpp Desktop/settings.h \
		Desktop/desktopapp.h \
		ui_desktopapp.h \
		Desktop/mytreetab.h \
		OraytaBase/bmarklist.h \
		OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		ui_settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o Desktop/settings.cpp

importbook.o: Desktop/importbook.cpp Desktop/importbook.h \
		OraytaBase/functions.h \
		ui_importbook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o importbook.o Desktop/importbook.cpp

desktopapp_bookmark.o: Desktop/desktopapp_bookmark.cpp Desktop/desktopapp.h \
		ui_desktopapp.h \
		Desktop/mytreetab.h \
		OraytaBase/bmarklist.h \
		OraytaBase/booklist.h \
		OraytaBase/book.h \
		OraytaBase/bookiter.h \
		OraytaBase/functions.h \
		OraytaBase/guematria.h \
		Desktop/bookdisplayer.h \
		Desktop/pdfwidget.h \
		OraytaBase/minibmark.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o desktopapp_bookmark.o Desktop/desktopapp_bookmark.cpp

qrc_Orayta.o: qrc_Orayta.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Orayta.o qrc_Orayta.cpp

moc_filedownloader.o: moc_filedownloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filedownloader.o moc_filedownloader.cpp

moc_bookfind.o: moc_bookfind.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bookfind.o moc_bookfind.cpp

moc_quazipfile.o: moc_quazipfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quazipfile.o moc_quazipfile.cpp

moc_minibmark.o: moc_minibmark.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_minibmark.o moc_minibmark.cpp

moc_bmarklist.o: moc_bmarklist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bmarklist.o moc_bmarklist.cpp

moc_desktopapp.o: moc_desktopapp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_desktopapp.o moc_desktopapp.cpp

moc_mywebview.o: moc_mywebview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mywebview.o moc_mywebview.cpp

moc_bookdisplayer.o: moc_bookdisplayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bookdisplayer.o moc_bookdisplayer.cpp

moc_addcomment.o: moc_addcomment.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addcomment.o moc_addcomment.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

moc_errorreport.o: moc_errorreport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_errorreport.o moc_errorreport.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

moc_importbook.o: moc_importbook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_importbook.o moc_importbook.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_icon: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/Orayta/ || mkdir -p $(INSTALL_ROOT)/usr/share/Orayta/
	$(QINSTALL) /home/dash/dev/Orayta-QT/Icons/Orayta.png $(INSTALL_ROOT)/usr/share/Orayta/Orayta.png
	$(QINSTALL) /home/dash/dev/Orayta-QT/Images/Wait.gif $(INSTALL_ROOT)/usr/share/Orayta/Wait.gif

uninstall_icon: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/Orayta/Wait.gif
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/Orayta/Orayta.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/Orayta/ 


install_trans: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/Orayta/ || mkdir -p $(INSTALL_ROOT)/usr/share/Orayta/
	$(QINSTALL) /home/dash/dev/Orayta-QT/Hebrew.qm $(INSTALL_ROOT)/usr/share/Orayta/Hebrew.qm

uninstall_trans: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/Orayta/Hebrew.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/Orayta/ 


install_css: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/Orayta/ || mkdir -p $(INSTALL_ROOT)/usr/share/Orayta/
	$(QINSTALL) /home/dash/dev/Orayta-QT/css $(INSTALL_ROOT)/usr/share/Orayta/css

uninstall_css: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/Orayta/css
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/Orayta/ 


install_menu: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/applications || mkdir -p $(INSTALL_ROOT)/usr/share/applications
	$(QINSTALL) /home/dash/dev/Orayta-QT/Orayta.desktop $(INSTALL_ROOT)/usr/share/applications/Orayta.desktop

uninstall_menu: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/Orayta.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install: install_target install_icon install_trans install_css install_menu  FORCE

uninstall: uninstall_target uninstall_icon uninstall_trans uninstall_css uninstall_menu  FORCE

FORCE:

